### ISSUE TITLE
Bad drops/rates for Avali crops

### ISSUE THREAD

**Issue by Cirian** [Avali-Triage-Team/Avali#128]
Avali crops are dropping very little actual food items, and a large amount of seeds.

**Comment by Fevix** [comment]
This is in the newest version? 

The newest version's drop tables SHOULD be giving much more food than seeds. Each plant is guaranteed a seed and a food, with a chance for another of each, weighted towards a second food

**Comment by thakyZ** [comment]
I have found I have been now getting less food than seeds.

**Comment by Devani1** [comment]
I've been getting way more food than seeds as of late, not sure if this is still an issue.
