### ISSUE TITLE
(On hold) Dyeing Clothes

### ISSUE THREAD

**Issue by Machaeus** [Avali-Triage-Team/Avali#135]
I don't appear to be able to dye Avali clothes.  Got any idea what's up?

**Comment by Fevix** [comment]
Development has been halted this issue will remain until a later date

**Comment by Fevix** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;5y5w9zGZ&#x2F;16-vanilla-clothing-changes-and-suggestions-for-clothing-to-modify"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Vanilla clothing changes and suggestions for clothing to modify</a>
