### ISSUE TITLE
(Worked on)Avali bows need new primaryAbilities

### ISSUE THREAD

**Issue by Fevix** [Avali-Triage-Team/Avali#213]
The new primaryAbilities should use the projectiles found in https://github.com/Fevix/Avali/tree/master/projectiles/guns/unsorted

I think it'd be possible to merge all of those into a single AvaliArrow folder and simply set the dps in the .activeitem file.

**Comment by UlithiumDragon** [comment]
Yeah you can use just one arrow projectile now. I made the mod before .activeitem existed.

I used the "avali plasma explosion" for the projectile collision iirc.

I also had tried to have the "arrows" have no drop-off originally, but it had some issues (i.e. short rapidly firing would leave behind projectiles that moved absurdly slowly, or slowed down once off the visibly rendered area of the screen).
Odds are I just used a bad "physics" mode that caused this issue.
