### ISSUE TITLE
MakeTungsten Block available on Nanolathe?

### ISSUE THREAD

**Issue by TheStatic** [Avali-Triage-Team/Avali#283]
A vast majority of the nanolathe recipes use tungsten blocks, but they are inaccessible until the titanium upgrade workbench (despite the fact that the starting workbench has tungsten recipes, oddly...) so it's a bit frustrating that you can't craft 80% of the things on the nanolathe unless you upgrade the unnecessary and optional workbench.

However, rather than edit and update all the recipes, a simplier solution would be to add a tungsten block recipe itself to the table, although you can balance it out by having the recipe give out less blocks per tungsten bar as a trade-off for not having to get the upgraded workbench.

**Comment by Jeadbe** [comment]
As an alternative, we could change the Avali block recipes to use tungsten bars instead of blocks. This would mean the recipes would need to be re-balanced. Thoughts, anyone?

**Comment by Urrurrual** [comment]
I was surprised when I saw it was tungsten blocks and not tungsten bars myself, but I think the rebalancing would be a bit tricky since fifty blocks constitute one bar and most recipes only call for an average of five blocks, which is one tenth of a tungsten bar. Might just be better to do this guy's suggestion IMO.

**Comment by Jeadbe** [comment]
The only recipes that might be made difficult would be the crafting stations (stove, kitchen, etc). But even putting them at 1 tungsten bar each still leaves them really cheap. All of the tile recipes are either 1 tungsten block to 1 Avali block or 1 block to 2 Avali blocks.
