### ISSUE TITLE
Graphical issues with the player.

### ISSUE THREAD

**Issue by knight73** [Avali-Triage-Team/Avali#308]
http://imgur.com/6MdsKFr
In that image, there are a few graphical issues I've seen. 
There's a pixel on a pose that doesn't get colored properly, some arms don't attach to the character (Float in front of them in their resting pose) and with the chest puffed out pose, some Avali armor has chest fluff poking out. I also think an arm might be out of position in the aforementioned clipping image, but I could be wrong.
((Just noticed the attach files thing as I typed this, but I'll leave that link as well.)) ((This is also my first time using github, if I did something wrong, sorry!))
![avali graphical issues](https://cloud.githubusercontent.com/assets/21232613/17955040/f594ccdc-6a33-11e6-8b00-61bf7cb971c0.jpg)

**Comment by knight73** [comment]
((On my phone now, can't edit)) in the image with the I colored pixel issue, the pose is the ones where the arms are out, (in the same style as the broken arm image)) and the tail is in a lowered position, but the char isn't slouching. I hope that helps you find the issue I mean.

**Comment by Fevix** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Ob2d71n1&#x2F;71-graphical-bugs"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Graphical bugs</a>

**Comment by Fevix** [comment]
Chances are a majority of these bugs will be fixed by Ryuujin when he finishes with the Avali rework.
