### ISSUE TITLE
Short swords and daggers not being recognized by other mods.

### ISSUE THREAD

**Issue by imfunnytoo** [Avali-Triage-Team/Avali#309]
Short swords and daggers aren't recognized by the Weapon Fusion and Weapon Reinforcer mods. I brought this up with the dev for the mods and he told me it was likely an issue with item tags for them specifically that they were likely missing the weapon tag. The rest of the weapons work with the mods so it has something to do with them specifically. I really enjoy using short swords/daggers and shields and not being able to power them up is a real bummer. Please work on this as fast as you can. Also despite it saying to include the log file on the mod page I don't think it would be necessary in this case as I would think this is a rather simple thing to address.  If the log file will help I'll gladly post it though.

**Comment by Fevix** [comment]
>8 months later
