### ISSUE TITLE
VBS2 Shard material cost

### ISSUE THREAD

**Issue by RoyalStarlord** [Avali-Triage-Team/Avali#310]
I noticed that when you use the separator device on the replicator, and that if you are trying to build the best 1 handed sword, it uses aegisalt instead of violium. Sure, it can still use solarium stars as normal, but using aegisalt?? Not normal for the separator crafting tables! : P

So yah, there's my two cents.

**Comment by thakyZ** [comment]
I will fix this because I have doubting suspicion on Ryujin's rewrite
