### ISSUE TITLE
Opening Contianor Crash

### ISSUE THREAD

**Issue by Pyro213** [Avali-Triage-Team/Avali#314]
I created a new Avali character, turn said character into a testing character.  Attempt to open my ship locker and I crash.  When back in and did it again, crashed again.  Tried to open a weapons chest on a planet, crashed.  I can supply a complete mods list

[http://pastebin.com/MWgX7ew7](url)

Different WidgetParserExpection crash
[http://pastebin.com/jnFtkxSC](url)

**Comment by Fevix** [comment]
"(WidgetParserException) Failed to find callback named: renameContainerReset"

issue is caused by a mod that allows renaming of containers.

**Comment by Pyro213** [comment]
Thank's, know the problem now
