### ISSUE TITLE
Issues with player sprite

### ISSUE THREAD

**Issue by ColorshyTheDull** [Avali-Triage-Team/Avali#317]
There is an issue with the player sprite being out of line with the arms. This seems to happen only when not wielding a weapon/matter manipulator
I took some screen caps with my two computers. 
Desktop:
![20160916140320_1](https://cloud.githubusercontent.com/assets/20571140/18598036/8b5bd73a-7c16-11e6-8d44-e44497989a79.jpg)
![20160916140244_1](https://cloud.githubusercontent.com/assets/20571140/18598038/8e517026-7c16-11e6-9644-e19706539204.jpg)
Laptop:
![20160916140653_1](https://cloud.githubusercontent.com/assets/20571140/18598186/1e0ae8e6-7c17-11e6-9e62-d2794da453aa.jpg)
![20160916140606_1](https://cloud.githubusercontent.com/assets/20571140/18598185/1e09ee5a-7c17-11e6-846c-1b1e46c15436.jpg)

and so did "Evil Poptart" on steam: ![evil_popstartuserimage](https://cloud.githubusercontent.com/assets/20571140/18597809/5013c080-7c15-11e6-94ad-f0d6edb28c5a.jpg)
I believe it has something to do with the differing personalities on the player characters.

**Comment by Fevix** [comment]
Base mod is getting a rewrite, this may likely be fixed in the new base mod.

**Comment by ColorshyTheDull** [comment]
This was only introduced in the recent update. A brash movement to jump on it so quick, no?

**Comment by Fevix** [comment]
We have not changed the species sprite.
