### ISSUE TITLE
I keep getting removed from my starter world and warped back to my ship.

### ISSUE THREAD

**Issue by deathrockoni** [Avali-Triage-Team/Avali#318]
[my log.zip](https://github.com/Avali-Triage-Team/Avali/files/491008/my.log.zip)

So I can't get this mod working no matter what I do, title says it all. Usually what happens is I beam down to the world, and when I go to far to the left or right, the world just stops rendering, freezes, then kicks me off. The problem is exclusive to any avali character I've tried to make and I shouldn't have any mods that would cause problems like this.
I have no idea what log to post, so I guess I'll just post them all.

**Comment by Fevix** [comment]
You didn't include the base starbound.log file. None of the files in this zip have the error in them.

**Comment by deathrockoni** [comment]
@Fevix 
I edited my comment and put in the right log

**Comment by Fevix** [comment]
`[03:00:28.365] [Error] WorldServerThread exception caught: (JsonException) No such key in Json::get("appliesWeatherStatusEffects")`

Nothing in this mod uses that json line.

**Comment by deathrockoni** [comment]
@Fevix 
Thank you for your response.
However, the only mod I can think of that might do something like that would be Frackin Universe, and that should work just fine with Availi.
It's the only race I'm having this problem with.

**Comment by Fevix** [comment]
It's not the race that's the issue, the world you're warping to chose a monster that doesn't have this line.

**Comment by deathrockoni** [comment]
@Fevix 
Made a back-up  and uninstalled Frackin Universe. I've been playing for a few hours now and no more problems. I guess FU screws with Avali some how, which is weird because I've heard of other players using the same two mods with no issue. But thanks again for the help!
