### ISSUE TITLE
Nanolathe issue.

### ISSUE THREAD

**Issue by TianInfinity** [Avali-Triage-Team/Avali#321]
So , i decided to open the Nanolathe and went all the icon to build a housing colony. But when i hit the chest icon (Storage) , the game went to a crash.

Resubbing didnt do a thing.
Here's the file source. All on ZIP since the crash file dont support here. 
Hope you can get that fixed.
[Avali Nanolathe Crash File Source.zip](https://github.com/Avali-Triage-Team/Avali/files/565620/Avali.Nanolathe.Crash.File.Source.zip)

**Comment by Moonlightneo** [comment]
I'm not sure what exactly causes this. I assumed it was related to purchasable pets. however i couldn't find it in your log so i cant say for sure. I managed to solve this for myself by using this http://steamcommunity.com/sharedfiles/filedetails/?id=748629459
I however, am using purchasable pets, maybe the regular version will fix your issue instead?

**Comment by TianInfinity** [comment]
I dont seem to sub that mod......  i'll give it a try when i have the time.

**Comment by Znex** [comment]
bug fixed can confirm that  Avali Drone Pet - Purchasable Pets Version  fixed nanolathe crash issue
