### ISSUE TITLE
Crash on load.

### ISSUE THREAD

**Issue by Nicholaiii** [Avali-Triage-Team/Avali#322]
http://hastebin.com/liqayopoxi.java

**Comment by Fevix** [comment]
Uninstall Dye Mod.

**Comment by Fevix** [comment]
Is this the only mod you have that adds NPCs?

**Comment by Fevix** [comment]
Alright, so Starbound updated a bit and there's some things we need to change. However, you have several mods that add NPCs (Which is what the game is complaining about), and you're the one one that's crashing (that I know of).

**Comment by Nicholaiii** [comment]
Yes, amongst them the Elunite mod and the ridiculously big gyrusens+ but they all seem to play fine together?

**Comment by thakyZ** [comment]
@Nicholaiii Does this error still happen?
