### ISSUE TITLE
exception thrown, shutting down: No such item 'avalipethouse

### ISSUE THREAD

**Issue by RealTabman** [Avali-Triage-Team/Avali#324]
Greetings.

When I try to craft a Avali container, Starbound crashes:
[20:34:45.346] [Error] Application: exception thrown, shutting down: (ItemException) No such item 'avalipethouse'
The crash occurs when I open the Avali Nano Printer (i think that was the name) and switch to the container tab, or when I open the shop from the "Enhanced Storage" mod and switch to the "all" tab. I'm running a few mods, most prominent probably "Fracking Universe" and "[Enhanced Storage](http://steamcommunity.com/sharedfiles/filedetails/?id=731220462)"

[starbound log](http://pastebin.com/t7Nk11w6)

If there is something else you need, please ask.
Thanks

**Comment by JustLikeAMetaphor** [comment]
Do you also have the Purchasable Pets: Avali Drone mod? I believe avalipethouse is part of that mod, which is broken and crashing since SB update 1.2

**Comment by Fevix** [comment]
What the above comment said. Avalipethouse is part of a separate note.

**Comment by RealTabman** [comment]
Just for your information, I previously never had the Avali Pet mod installed and installing it changes the crash reason to:
[12:56:44.632] [Error] Application: exception thrown, shutting down: (ItemException) No such item 'ancientbigchest'
I suspect that it's rather a problem with the "Enhanced Storage" mod.
Thanks again for the help.
