### ISSUE TITLE
CTD when using nanolathe

### ISSUE THREAD

**Issue by Ayjay47** [Avali-Triage-Team/Avali#328]
Game CTD when opening the Containers tab on the nanolathe.
Are active mods visible on the crashlog? If not i'll link them up here too.
[starbound.txt](https://github.com/Avali-Triage-Team/Avali/files/720804/starbound.txt)

**Comment by Fevix** [comment]
the item "avalipethouse" is not referenced by this mod. I suspect one of the other mods is referencing it.

**Comment by Ayjay47** [comment]
I did some looking up, and it turns out installing the "Avali drone pet - Purchasable pets edition" along with the "Purchasable pets" mods fixed the issue, why'd i have this recipe without ever touching this mod is beyond me, but i'm glad i found something.
