### ISSUE TITLE
[Error] Could not instantiate item '[avaliguardchest, 1, {"colorIndex":3}]'. (ItemException) No such item 'avaliguardchest'

### ISSUE THREAD

**Issue by Dracheneisen** [Avali-Triage-Team/Avali#334]
Hi, discovered that in my log, Keeps repeating that (line 434 then further).
Here it is : https://pastebin.com/ugQxT09x

**Comment by Devani1** [comment]
I'll take a look at that item. It's original purpose was to give the npcs a form of armor because they couldn't have a vanity slot to have normal looking clothing. I'll see if I can make that error disappear by either looking at the default spawn config or the item itself (If it still exists).

**Comment by ThreeTen22** [comment]
Oh nice, I was just going to comment about this too.
I did some research on my own and heres what I came up with if its of any help:

There seems to be two options you can use,
 _avaliguardtier1chest_,
items\armors\avali\avali-guard_armor
 _avalitier1chest_,  
items\armors\avali\avali-tiered

the config file with the issue where  is:
npcs\guard.npctype.patch


with the code:
`    [ [0, [ {
        "head" : [ 
          { "name" : "avaliarmor1head", "data" : { "colorIndex" : [3] } },
          { "name" : "avaliarmor2head", "data" : { "colorIndex" : [3] } },
          { "name" : "avaliarmor3head", "data" : { "colorIndex" : [3] } }
        ],
        "chest": [ { "name": "avaliguardchest", "data" : { "colorIndex" : [3] } } ],
        "legs" : [
          { "name" : "avaliarmor1pants", "data" : { "colorIndex" : [3] } },
          { "name" : "avaliarmor2pants", "data" : { "colorIndex" : [3] } },
          { "name" : "avaliarmor3pants", "data" : { "colorIndex" : [3] } }
        ],
        "primary" : [
          { "name" : "avaliminigun", "data" : { "level" : 4 } },
          { "name" : "avalirifle", "data" : { "level" : 4 } },
          { "name" : "avalishotgun", "data" : { "level" : 4 } },
          { "name" : "avalipistol", "data" : { "level" : 4 } }
        ],
        "sheathedprimary" : [
          { "name" : "avalitier4shortsword" }
        ],
        "alt" : [
          { "name" : "avalipistol", "data" : { "level" : 4 } },
          { "name" : "avalitier4barrier" }
        ]
      } ] ]
    ]`

So if I had to guess just replacing the chest array with something like
```
        "chest" : [
          { "name" : "avaliguardtier1chest", "data" : { "colorIndex" : [3] } },
          { "name" : "avaliguardtier2chest", "data" : { "colorIndex" : [3] } },
          { "name" : "avaliguardtier3chest", "data" : { "colorIndex" : [3] } }
        ]
```
or
```
        "chest" : [
          { "name" : "avalitier1chest", "data" : { "colorIndex" : [3] } },
          { "name" : "avalitier2chest", "data" : { "colorIndex" : [3] } },
          { "name" : "avalitier3chest", "data" : { "colorIndex" : [3] } }
        ]
```
should do the trick :D

**Comment by Dracheneisen** [comment]
Ok, thanks. It doesn't seem to have any negative impact in-game (except spamming the log), but still, I thought it was worth pointing it out.
