### ISSUE TITLE
Avali Clothing/Other Clothing, Mods, Main etc,

### ISSUE THREAD

**Issue by Darkcobra940** [Avali-Triage-Team/Avali#337]
The issue is that Avali's tails and heads or sleaves? keep popping out of clothing, armour,cosmetic armour or clothing and others, this is bugging me sence me and my friend have a server, and we have to characters for it each, a survival one, and a Admin one, mine are both Avali's so this gets annoying when i wear my armour or cosmetics, as even the legs clip threw it,While running legs duplicate and you have your avali legs behind the normal legs in armour or clothing cosmetics. and other times, when i run the sleaves glide behind me and my tail pops out, im fine with the tail, but the sleaves legs and head feathers need to be fixed. so if you can make something for this, that would be very helpful for me and my friends and most likely, other people.

**Comment by Fevix** [comment]
Fixing this would require removing a big part of what makes the avali unique: the custom body design. If you would like a specific armor set remade for the avali shape, head to the Trello and make a suggestion on the appropriate card.
