### ISSUE TITLE
When will be fixed graphite?\Когда будет исправлен графит?

### ISSUE THREAD

**Issue by Shurik1236** [Avali-Triage-Team/Avali#343]
Когда вы уже исправите этот конфликт с Frackin' Universe?
Неужели нельзя переименовать "Graphine" в "AV_Graphine"?
Не тонны же строк кода переписывать придётся.
Давно бы уже исправили...
(Google)
When you will fix this conflict with Frackin' Universe?
Is it not possible to rename the "Graphine" in "AV_Graphine"?
Not tons of lines of code to rewrite would have.
Would already have fixed...

**Comment by Shurik1236** [comment]
Если что, я тут решил исправить сам, так как у вас вижу руки не доходят.
Графит из FU работает и из вашего мода тоже. Просто предмет переименовал в AV_graphine и везде где он использовался тоже.
Версия последняя.
https://drive.google.com/file/d/0B0MN_3DSBdpDeTBKZTN5YTFfd1U/view?usp=sharing
По идее это вы должны были сделать.
(Google)
If anything, I've decided to correct myself, as you see the hands do not reach.
Graphite from FU works and from your mod too. Just an item renamed AV_graphine and wherever it was used, too.
Version last.
https://drive.google.com/file/d/0B0MN_3DSBdpDeTBKZTN5YTFfd1U/view?usp=sharing
The idea is you're supposed to do.

**Comment by Fevix** [comment]
This is already fixed in the latest, currently unreleased version, which is scheduled to be put out this Friday.
