### ISSUE TITLE
Avali rail platform errors out the world instance when loaded.

### ISSUE THREAD

**Issue by Argonius-Angelus** [Avali-Triage-Team/Avali#356]
[starbound.log.txt](https://github.com/Avali-Triage-Team/Avali/files/1065913/starbound.log.txt)

The Avali pet and tech station errors do not cause any issues in-game, but as soon as the rail platform is loaded in, the world instance crashes and you're sent back to the ship.

**Comment by Tanzmania** [comment]
Same issue as Argonius, I found that toggling off the "avali rail interaction mod" also helped the platform stop teleporting me back to ship. If that mod is enabled I could not find a way to get the rail to "break" to cause the auto-teleport loading to stop.

[starbound.txt](https://github.com/Avali-Triage-Team/Avali/files/1066792/starbound.txt)

In this file, I am loaded next to a rail. I attempt to place the areogel rail down and get sent to my ship. I load to a near-by teleporter, try to walk back into the area and get sent back to the ship. I quit and reload then the platform is on the ground.

**Comment by JennyLeeP** [comment]
Hello , I am the author of the "Avali rail interaction mod" .  I can confirm this issue. 
Placing a platform on a ship crashes the game .
Removing my mod and any others that effect rails does not prevent the crash.
Mostly just commenting here to so I can follow this and get my mod updated as soon as it is fixed.
Looks like it is mostly related to the new vehicle elevator code in the base game.
[starbound.txt](https://github.com/Avali-Triage-Team/Avali/files/1066846/starbound.txt)

**Comment by Fevix** [comment]
Nope, it's related to the new states they added to the rail platforms. Ours didn't have an "off" state, and after fixing it I discovered another change they made, adding a specific "off-rail" state in the frames file. 

I've fixed both of those in 688a5e094773d3145bbc34d9f6045c68f739b721

**Comment by JennyLeeP** [comment]
Awesome  , Thank you !

**Comment by JennyLeeP** [comment]
@Fevix   Any idea when this fix will be pushed to steam ?
Thanks again !

**Comment by Fevix** [comment]
Soon. Have some other things I want to bundle in to the next update.
