### ISSUE TITLE
Issue with the Nanolate

### ISSUE THREAD

**Issue by Kiglirs** [Avali-Triage-Team/Avali#357]
I'm having an issue with the Avali Nanolate. When i click on the chest icon, my game crash.
I've found this in the log: 

> [03:53:24.079] [Error] Could not instantiate item '[avalipethouse, 1, {}]'. (ItemException) No such item 'avalipethouse'
[03:53:24.093] [Error] Could not create blueprint item from recipe: (ItemException) No such item 'avalipethouse'

I've add the log. Btw i have other mods installed, but it did the same thing without these mods and it did it 1.2 too. (i'm in 1.3)

Here's the starbound.log: https://pastebin.com/0dbzZzc2

**Comment by Fevix** [comment]
The Avali mod does not reference "avalipethouse" anywhere in its code.

**Comment by Kiglirs** [comment]
I'm still having issues with the chest menu of the Nanolate. Idk where it could from :/
