### ISSUE TITLE
Avali tenants not moving in

### ISSUE THREAD

**Issue by GaleTheWhale** [Avali-Triage-Team/Avali#358]
I've been trying to build an avali settlement, and I can get vanilla race tenants just fine, but for some reason once I add furniture tagged with avali I can't seem to attract a tenant. I don't receive an error on the deed indicating that the room doesn't meet the requirements, it just sits there scanning. I had no problem previous to 1.3.

Log:  https://pastebin.com/d9Yn27k9

**Comment by Fevix** [comment]
Sorry for the delay. 

I've looked through the log and can't find any errors. Can you take a screenshot of the space you're trying to move a tenant into?

**Comment by Fevix** [comment]
Closing this issue due to lack of response and the fact that there are no errors visible in the log.
