### ISSUE TITLE
A missing file...

### ISSUE THREAD

**Issue by Artanis00500** [Avali-Triage-Team/Avali#359]
It seems my json file for the ships navigational console is missing,how do i fix that?(when i try to use the captains char i get an error stating the JSON file is missing)

**Comment by Fevix** [comment]
Is both your Starbound and your avali up to date?

**Comment by Artanis00500** [comment]
My starbound sais its version 1.2.4(my dad had to download it instead of purchasing it because he wont pay ;-;)and the avali mod is version 1.3.1

**Comment by Artanis00500** [comment]
Are you still there?If you're ever gonna read this again,here's the EXACT error prompt given when attempting to open the navigation interface
![starbound_2017-06-16_16-01-22](https://user-images.githubusercontent.com/29422354/27229790-36c61942-52ad-11e7-8a24-8f3d7cf84a4c.png)

**Comment by Fevix** [comment]
The current version only works on 1.3.1 due to changes they made to the captains chair.
