### ISSUE TITLE
Error putting a avali rail on ship

### ISSUE THREAD

**Issue by Drakenguy** [Avali-Triage-Team/Avali#360]
Trying upgrading the ship with some rails to make things easier but now and when i put one of the avali ones the world crashes and a message tells me its corrupted or something like that, now i can't enter my game because everytime it gives me that message

**Comment by Fevix** [comment]
I'm going to need the Starbound.log from when the crash first happened

**Comment by Drakenguy** [comment]
Trying to, but it says that the file type is not supported

**Comment by Fevix** [comment]
Open it in a text editor like Notepad and copypaste it into a new paste on Pastebin and give me the resulting link.
