### ISSUE TITLE
Material texture file name error

### ISSUE THREAD

**Issue by djkiourtsis** [Avali-Triage-Team/Avali#362]
The avalislopeddarkpannel.material is using avalislopeddarkpanel.png, which does not exist.

[starbound_server.log.txt](https://github.com/Avali-Triage-Team/Avali/files/1099406/starbound_server.log.txt)

**Comment by bsambrone** [comment]
I have the same error as well

**Comment by Fevix** [comment]
Blame Dawn for this, she doesn't know how to spell.
Fix incoming.
