### ISSUE TITLE
Server Crashing At Startup 

### ISSUE THREAD

**Issue by fajoaq** [Avali-Triage-Team/Avali#367]
Suddenly server (using PenGUIn) crashing at startup. Error is pointing to 
'/objects/biome/scorchedcity/scorchedcityfridge/scorchedcityfridge.object'
and
/tiles/materials/avalislopeddarkpanel.png

https://pastebin.com/sqEEbqvt

**Comment by Fevix** [comment]
Redownload, this was fixed in a stealth update
