### ISSUE TITLE
Avali Crops in FU not registering as a valid ingredient in Avali Foods

### ISSUE THREAD

**Issue by Starblast16** [Avali-Triage-Team/Avali#369]
The FU version of the Avali crops don't register as valid ingredients for Avali recipes, is it possible to fix this?

**Comment by Fevix** [comment]
Frackin Universe crops are different from Avali crops. They may share a name and sprite, but internally they are treated as entirely separate things.

There are currently no plans to fix this, though I may see about adding recipes to turn the FU versions into regular versions. This is low on the priority list right now, though.
