### ISSUE TITLE
avali introduction mission, when I interact with the first weapon container i get a fatal error

### ISSUE THREAD

**Issue by WolfieMate** [Avali-Triage-Team/Avali#372]
[starbound log 4 glitch - Copy.txt](https://github.com/Avali-Triage-Team/Avali/files/1147358/starbound.log.4.glitch.-.Copy.txt)

**Comment by Fevix** [comment]
Log doesn't tell me enough. It's not your fault, but i'm going to have to do some digging.

**Comment by StarboundFreek** [comment]
A friend of mine got this error before and we had one mod on and all the mod did was add a few songs for the instruments sooo... it might be a starbound thing...
