### ISSUE TITLE
Invisible barrier between floors

### ISSUE THREAD

**Issue by Torterenek** [Avali-Triage-Team/Avali#379]
Hello. I have used this mod for a while, and i just recently got back to playing Starbound. I started up my Avali character today, and the first time I tried to play him, the game exited with no error report. i tried a second time, and i got in, but my entire ship's bottom floor is blocked by an invisible barrier right under my doors. I tried mining it, and ended up destroying my back wall under the barrier. I also have a crew member trapped down there. can you help me out?

**Comment by Fevix** [comment]
Can you take a screenshot of the area?

**Comment by Torterenek** [comment]
yes. just barely did.
![avali ship 2](https://user-images.githubusercontent.com/31908155/30405337-6ea94bae-98a8-11e7-9745-9fd52980ac75.jpg)
![avali ship](https://user-images.githubusercontent.com/31908155/30405339-717e78d6-98a8-11e7-8ad6-5b251dbe54a9.jpg)

**Comment by Fevix** [comment]
Try placing blocks there then mining them back up. If that doesn't work,
look for a mod that can remove invisible doors. Someone else had that same
problem and told me that's how they fixed it
