### ISSUE TITLE
avikan antena?

### ISSUE THREAD

**Issue by Zthespook** [Avali-Triage-Team/Avali#380]
https://pastebin.com/9kSVZ8g7

some kind of crash,  friend has mod but isnt effected by what ever it was...

**Comment by Fevix** [comment]
Wrong mod. You want the Elithian Races Mod: 
https://community.playstarbound.com/resources/elithian-races-mod-a-starbound-expansion.3019/
https://steamcommunity.com/sharedfiles/filedetails/?id=850109963
