### ISSUE TITLE
Server Console Spammed with Error when Trying to Connect with Avali Character

### ISSUE THREAD

**Issue by SynsCity** [Avali-Triage-Team/Avali#384]
[starbound_server.log](https://github.com/Avali-Triage-Team/Avali/files/1485190/starbound_server.log)
When I try to connect to my server with an Avali character the game endlessly loads while the console spams the same message forever, even after closing the game and cancelling the connection (which makes the game itself stop responding and need to be forcefully closed). This doesn't happen when I try to connect using a human character. I have the game and mod installed via Steam.

**Comment by Fevix** [comment]
Server does not have Avali installed.

**Comment by SynsCity** [comment]
How do I install it on the server then? I was told that Steam has the server and client use the same mod files.

**Comment by Fevix** [comment]
Whoever's hosting the server needs the mods installed to their client. The server and client both look to the same places for mods. 

I'm not sure if workshop mods are supported.

**Comment by SynsCity** [comment]
I found a batch script that symlinks the mods from their steam workshop folder to the client mods folder so its all good.
