### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by KelvinShadewing** [Avali-Triage-Team/Avali#387]
There's no license file, nor any mention of it in the readme, so what is the license for the code? Assets? Avali species itself? It's really hard to work with a thing when you aren't even sure what you're allowed to do with it.

**Comment by Fevix** [comment]
The Avali species is not mine, nor was this mod initially created by me. I wouldn't feel right applying a license to something that isn't mine. 

However, if forced to choose, I've been operating as if this work was licensed under GNU GPLv3 (More or less unrestricted permissions, but all derivatives must be distributed under the same license)

**Comment by KelvinShadewing** [comment]
Ah. I've looked for information on it on the wiki and in the creator's posts, even asked him myself, but have found nothing so far.
