### ISSUE TITLE
Crash on ChuckleFish logo.

### ISSUE THREAD

**Issue by Daiquiris** [Avali-Triage-Team/Avali#389]
[starbound.log](https://github.com/Avali-Triage-Team/Avali/files/2084001/starbound.log)
Crash is immediately following chucklefish logo, isolated the issue to avali triage mod through process of elimination. (xbawks works without avali triage or any other mod, when avali triage is added so there are only two mods the crash happens 100% of the time.)

**Comment by Jon1128** [comment]
Not sure if help is still required for this but I would head on over to the Starbound forums and download the latest version [here](https://community.playstarbound.com/resources/avali-triage.2852).

The issue was that you were missing '/animations/shards/avalihoverbikeshard.animation'.

**Comment by Fevix** [comment]
Actually this issue happens a lot and I have no idea why. This is like the
20th person to come up to me with it.

**Comment by Daiquiris** [comment]
I figured it out, my folders were wrongly set up,
(starbound/mods/avali-triage/avali-triage/mod files) Changing it to
(starbound/mods/avali-triage/mod files) fixed it
