### ISSUE TITLE
Tiered armor gives next tier armor recipe to non-avali characters.

### ISSUE THREAD

**Issue by AeolusDraco** [Avali-Triage-Team/Avali#391]
When a non-avali character picks up a tiered avali armor, they learn the recipe for the next tier of that armor.
Is this intended?

**Comment by Fevix** [comment]
It was originally intended that avali would go through the tiers one by one, learning them in order, so they couldn't skip tiers. This was achieved by putting the next tier in the 'learned on pickup' list for the armor. 

Honestly, we could probably change this behavior.

**Comment by AeolusDraco** [comment]
While do find it strange, as picking up vanilla armor does not give any recipes.
I noticed it as it is inconsistent:
`$ cd items/armors/avali/avali-tiered`
`$ grep -nr learnBlueprintsOnPickup`
`./avalitier1.chest:76:  "learnBlueprintsOnPickup" : [ "avalitier2chest" ]`
`./avalitier1.head:68:  "learnBlueprintsOnPickup" : [ "avalitier2head" ]`
`./avalitier1.legs:66:  "learnBlueprintsOnPickup" : [ "avalitier2pants" ]`
`./avalitier3.chest:76:  "learnBlueprintsOnPickup" : [ "avalitier4chest" ]`
`./avalitier3.head:68:  "learnBlueprintsOnPickup" : [ "avalitier4head" ]`
`./avalitier3.legs:67:  "learnBlueprintsOnPickup" : [ "avalitier4pants" ]`

This means that it only occurs for tier 1 and tier 3,
teaching the recipe for tier 2 and tier 4 respectively.

However since avali already know all the tiers of their armor recipes this is only noticeable if a non-avali character picks up one of the affected tiers of avali armor.
