### ISSUE TITLE
What is the last Update?

### ISSUE THREAD

**Issue by xMrCaosx** [Avali-Triage-Team/Avali#395]
Hi!, im user in Steam and i have this mod from the Workshop.

But it's possible other recents updates, outside from Workshop?
or the latest update is from 24 June 2017?

**Comment by Fevix** [comment]
All three versions of the mod are identical. There have been updates to the
developer branch, but they are not quite ready for release

**Comment by xMrCaosx** [comment]
ohhh great!, thanks :3
