### ISSUE TITLE
New bug, or a mod conflict? - I call it "Endless Starvation".

### ISSUE THREAD

**Issue by doomrider023** [Avali-Triage-Team/Avali#402]
Alright, I spent like three days troubleshooting a new modpack I put together. I had a strange issue that all characters regardless of difficulty or race, would load in with perpetually zero hunger (unable to be removed by admin or food) and the starvation effect. So basically it was starve, respawn, starve, respawn, etc.
Anyways I on a whim removed all the avali mods I had, and low and behold, the bug is gone.
I believe there could be a conflict between the mods, or a disastrous bug of some sort. Have there been any recent patches or updates?
Anyways, here, I'll link my modpack, and I have an image to show that I am in casual and still starving without a hunger bar.
Modpack:
https://steamcommunity.com/sharedfiles/filedetails/?id=1717884438
Proof Image
https://steamuserimages-a.akamaihd.net/ugc/823506058663102006/B09367A2EAF5C85C44DFE590AAA9303DC969C188/

**Comment by Fevix** [comment]
Please provide a log of you from launching the game to your first respawn

**Comment by doomrider023** [comment]
I was wrong, it's not Avali, and I don't have a log now since it works. I
have no clue what's up with my pack. My friends are having issues with it
and I'm not and we all have the same mods. you are welcome to test my pack
though if you want.
I can't understand logs at all...

**Comment by doomrider023** [comment]
Ahem, sorry, I mean't to say the "same" issue.
