### ISSUE TITLE
Crashes Linux SB Server On Startup, "readFull End of File" Error

### ISSUE THREAD

**Issue by CrabDeSass** [Avali-Triage-Team/Avali#404]
I've done some searching around prior and digging through the error log generated beforehand (which I will link via Pastebin for what it's worth), but neither have been helpful. It's been a while since I've done this so I know some things have changed, notably the last time was before 2017, the most recent update to this mod.

I've deduced that Avali Triage is a culprit, based on emptying and gradually readding mods, have double checked for corrupt FTP uploads, tried clearing out old Universe files, etc. Unfortunately the crash occurs [i]on launch of the Starbound Linux server executable[/i], before the terminal output lists any mods as loaded, so neither it nor the crash log are helpful to my eyes. The majority of search results for EoF errors are either "known Frackin Universe errors" (which for clarity I am trying to use in conjunction) wherein corrupted planet files are suspected, wiped, and the problem is resolved (not applicable here), or date from the MP related updates in 2015 (and appear to all be errors given to players trying to connect to a server, not from the server itself failing to launch).

Any more experienced insight is appreciated, I imagine this might is either a fringe issue or PEBKAC due to being more experienced in Linux than Starbound modded servers. If it matters, this is a remote virtual server instance, Ubuntu 16.04, with 8GB VRAM.

https://pastebin.com/2qHPKkHJ

**Comment by Fevix** [comment]
I have no access to a Linux machine and cannot reproduce or attempt to
diagnose this issue. I will, however, forward this report to others who may
have such access or perhaps knowledge on potential fixes.

**Comment by Fevix** [comment]
A few possibilities brought up by @katana#0009 on Discord: 

> worth checking to see if there is a BOM on the file perhaps, check to see if it's caused by symlinks or weird filesystem behaviors

> could be a oddly failed read due to lack of perms to read?

> tbh I'd unpack and repack all files too
