### ISSUE TITLE
Entrance Decorative and non are not platform-able and weather through-able 

### ISSUE THREAD

**Issue by rogelio1985** [Avali-Triage-Team/Avali#412]
hi first time making a issue report.

I'm using the steam version and see a issue with the tent pieces like the decorative and the non-decorative entrances seems to be not platform-able and weather and the effects goes through. even    my avatar character. 

here are my attached files in case. If I'm missing other files to share. please let me know. 
![20190901135616_1](https://user-images.githubusercontent.com/54781699/64082975-a54a1080-cccc-11e9-84a1-42ca058fc9cc.jpg)
![20190901135734_1](https://user-images.githubusercontent.com/54781699/64082976-a5e2a700-cccc-11e9-9fd1-6345d084420c.jpg)
[starbound.log](https://github.com/Avali-Triage-Team/Avali/files/3563978/starbound.log)

![20190901152924_1](https://user-images.githubusercontent.com/54781699/64083019-649ec700-cccd-11e9-95f6-60b88e6e0aa1.jpg)

**Comment by Fevix** [comment]
Functioning as intended. The pieces you have on the bottom there are indeed
platforms that weather passes through, and the roof pieces are indeed meant
to block weather and players.

**Comment by rogelio1985** [comment]
ah. good to know. thank for you for the confirmation reply.
