### ISSUE TITLE
Coloriser not working

### ISSUE THREAD

**Issue by SpringsSong** [Avali-Triage-Team/Avali#415]
[starbound.log](https://github.com/Avali-Triage-Team/Avali/files/3838028/starbound.log)

Specific relevant excerpt: [20:43:50.587] [Error] Could not load image asset '/objects/avaligeneric/table/avalitable3.png:purple', using placeholder default.
(AssetException) No such frame purple in frames spec /objects/avaligeneric/table/avalitable3.frames

Tried recoloring both avalitable3 and avalichair2; both turned invisible when I recolored them. I had initially had Avali Colored Items and Avali Colored Items add-on installed, but for testing purposes, I disabled them, as shown in the log file. Examining the file specified in the error, it shows that there is no `purple` frame specified for the table, or anything aside from `default` for `avalichair2`

**Comment by SpringsSong** [comment]
Upon investigating the files, this seems to be because in every file that *does* have colors enabled, there's an option for `pink`, but in the Coloriser's files itself, it's looking for `purple`.

**Comment by Fevix** [comment]
Solved in bbca3ff664dd7e45dc4e25d29b04fb5a1f98f8da
