### ISSUE TITLE
Fixes/changes towards missed elements

### ISSUE THREAD

**Issue by JulesMerit** [Avali-Triage-Team/Avali#446]
Been thinking and asking lots of people about the game content, and i really think Developers should pick their attention on some missing/unchanged stuff that havent been changed from its very beginning(?):

**1. Death animation part**
 - Avali has "default" reviving from death animation that kind of doesnt seems to fit or just work by itself, even just copying the avians' reviving animation should do, or if you clever enough - make an advanced one as the mod itself is decently huge for that matter.

**2. Race silhouette in tech upgrade console**
 - Tech upgrade console has human silhouette by default compare to any other race.
 
**3. Interaction speech voices**
 - Avali NPCs has default human voice sounds when interacting with them, which should _probably_ be as avians instead? If not, just like with the first issue - make a custom one if possible.

So far - these issues are _the most noticable_ so please, take a bit of a time to fix or/and change them for good, players will be very thankful for you on these small details!

**Comment by Fevix** [comment]
The death animation is a very complex animation and requires someone with a much greater knowledge of starbound animations than I have to prepare. This is very low priority. 

That said, the race silhouette... should exist? I could have sworn we did that. 

Interaction speech is certainly also a potential fix. I'll probably use your suggestion and change it to avian until we can get a custom sound made.
