### ISSUE TITLE
Looks like a block ID conflict

### ISSUE THREAD

**Issue by Doodlinka** [Avali-Triage-Team/Avali#450]
![image](https://user-images.githubusercontent.com/62027005/122586761-bb71be00-d065-11eb-9a7d-993da979b635.png)

the orange platform spawns where it shouldn't, it gives avalidarkplatform when broken, placing it yields orange platform when diagonal and black platfom when straight. this wasn't an issue about 2 months ago (i think) when i last played this mission

**Comment by Fevix** [comment]
Will look into it when I get home

**Comment by Fevix** [comment]
What mission is this? We don't add any missions in the avali mod.
