### ISSUE TITLE
Assembly Terminal Still Requires Deprecated Circuit Board

### ISSUE THREAD

**Issue by Fuegofandango** [Avali-Triage-Team/Avali#452]
![Screenshot 2021-10-14 200413](https://user-images.githubusercontent.com/55003217/137425809-f9c7fabe-5ae0-4a98-aacc-375658522fef.jpg
[starbound.log](https://github.com/Avali-Triage-Team/Avali/files/7350608/starbound.log)
)

The Avali Assembly Terminal is still requiring (for me at least) the old circuit board that was deprecated in an update to the base game. I saw you posted a response to this issue over a year ago saying to use the new silicon board but in the screenshot provided I have one in my inventory and it's still not allowing me to create one. I am using additional mods.

**Comment by Fevix** [comment]
The Assembly Terminal is not an object added by this mod.
