### ISSUE TITLE
avali not showing up in character selection and my avali file is gone

### ISSUE THREAD

**Issue by wantabeez** [Avali-Triage-Team/Avali#454]
I get the feeling that I've installed too many mods and left it alone for a few months and borked it, did try to uninstal some more risque mods for the sake of playing with friends, but putting them back doesn't seem to help so I don't know what to do. 
[starbound.log](https://github.com/Avali-Triage-Team/Avali/files/7420190/starbound.log)

**Comment by Fevix** [comment]
I know it's been a while, but the Avali Triage mod does not appears in your list of mods.
