### ISSUE TITLE
Avali Triage makes my game crash during start

### ISSUE THREAD

**Issue by SomeWierdNinja** [Avali-Triage-Team/Avali#465]
Hello Fevix

I recently redownloaded Starbound and started to redownload a shiton of mods that I played a lot with my old computer. I now have a new one and for some reason the game doesn't launch when Avali Triage is installed. For all I have been able to figure out, it messes with lots of mods like squamaeft and it just crashes the game. It's wierd cus not so long ago, I had no issues having these mods together and they worked just fine. Could you look into it and help fix thix issue ?

here's a pastebin link for you to look at the log : https://pastebin.com/bnrVWHqV

**Comment by SomeWierdNinja** [comment]
I downloaded it from steam btw

**Comment by Fevix** [comment]
Looks like you have issues with duplicate projectiles and something about
"redenergyblade" throwing errors too.

This log does not contain a crash.

**Comment by SomeWierdNinja** [comment]
hello, thanks for the response !
That's weird cus the game clearly closed on start...
Maybe I put the wrong log in it. I'll try another one. As for the duplicates, a lot of them appear after avali triage is installed for some reason ? Even tho the game seams to accept avali plus just fine without Avali triage...
It probably comes from conflicts or items that might have IDs similar to the one in avali's mod but since I know nothing about programming I can't understand anything...

I'll put in another log where the game shutsdown at start after having avali triage installed : https://pastebin.com/fY0GSUn4

sorry for the inconvenience, like I said earlier everything worked fine a while ago and now there are conflicts popping everywhere for no reason

**Comment by SomeWierdNinja** [comment]
f*ck I messed up somthing with the discussion, hope I didn't close it by accident

**Comment by Fevix** [comment]
It's fine.

[08:07:02.597] [Info] detected supported OpenGL texture size 16384, using
atlasNumCells 256
[08:07:23.854] [Info] Application: quit requested

These lines near the end of the log tell me the game was running fine for
about 20 seconds before someone clicked the X or pressed Quit on the main
menu.

The log you're looking for is the one without any number behind it.
(starbound.log not starbound.log.1)

**Comment by SomeWierdNinja** [comment]
Wierd, because it is the one without numbers behind it that I pasted to the bin... so maybe it just quit by itself ? Is that even possible

**Comment by SomeWierdNinja** [comment]
Hello Fevix
Sorry for the delay I was busy and couldn't touch my game for a time being
So I took a quick look and tried to do some research to find if there were any known issues about mods conflicting with avali and found nothing of the sort...
I hope I put the link for the right log this time so you can take a look if you want. It is wierd tho because I don't know what is wrong with the game since all of these mods worked well together in the past.
Here :https://pastebin.com/vpPkRpUY
I'll try to take another look on the side in hopes to find what the hell is messing with the mod on my side

**Comment by Fevix** [comment]
`[11:28:22.940] [Error] Application: exception thrown, shutting down: (TreasureException) Duplicate TreasurePool config 'dragoontreasure' from file '/treasure/avali.treasurepools'`

You have a mod that's adding a treasure pool a second time. Unfortunately due to the size of the mod lost I can't help narrow it down. Recommend disabling your avali addon mods one by one until the problem resolves, then reenabling app but the lady one

**Comment by SomeWierdNinja** [comment]
Thank you for the help! I have found the mod that made the whole thing crash and it was the Asari mod! The issue has already been reported and the dev just never fixed it so now it works !

Good luck for you and the team for your next projects !
