### ISSUE TITLE
Elite certificate uncraftable

### ISSUE THREAD

**Issue by BanhammerUA** [Avali-Triage-Team/Avali#470]
Elite certificate don't show in craft list on avali crafting station, even with admin mode.
Also vanilla later game weapons and equip don't show when need module installed, not sure if it bug or supposed to work like this.

**Comment by Fevix** [comment]
TUrns out the recipe was disabled and no new way to learn the pilum was implemented. 

You'll now learn the t3 pilum by picking up a t2 pilum.
