### ISSUE TITLE
(ItemException) No such item 'biohalohead'

### ISSUE THREAD

**Issue by DV-Prof-Program** [Avali-Triage-Team/Avali#477]
When I try to access the clothing tab of the nanoloom, the game immediately crashes with the final error message reading: [Error] Application: exception thrown, shutting down: (ItemException) No such item 'biohalohead'.

When I looked back at the rest of the log, I found this related error as well: [Error] Could not instantiate item '[biohalohead, 1, {}]'. (ItemException) No such item 'biohalohead'

**Comment by Fevix** [comment]
We do not add the item biohalohead, nor do we have a recipe for this item.
(A mod adding the recipe but not the item would be the cause for this)

**Comment by Fevix** [comment]
'biohalohead' is not an item or recipe added by this mod. (A mod that adds the recipe, but not the item (or if the item errors and doesn't load) would be the cause of this crash)

**Comment by DV-Prof-Program** [comment]
Alright, I initially thought it was this mod since it showed up in the nanoloom, but you have helped me narrow down what it could be, thanks.
