### ISSUE TITLE
Fix for avali cushion sitting position being offset by 1 block

### ISSUE THREAD

**Issue by Chaya2766** [Avali-Triage-Team/Avali#483]
In the current state, the avali cushion (object avalicushion1) cannot be sat on properly. As you can see on the images below, the character on the right is sitting in a wrong position (appears offset by 1 block).

![before_sitting](https://github.com/user-attachments/assets/7d3d5b71-3d53-4c5f-950c-c8a1dbf45758)
![before_notsitting](https://github.com/user-attachments/assets/3b1292c4-1e20-44c9-a255-a308814d6f9e) ![before_boxes](https://github.com/user-attachments/assets/2b97ac3c-0bf0-4651-9ddb-d154a4a4fc5d)

In my attempts to fix this I could not find a way to do so by simply changing the sitting position - either the right or the left character always appeared to be sitting in the wrong place by 1 block. The only fix I could come up with that actually seems to work is changing the "imagePosition" property from [-8, 0] to [-12, 0]. Results can be seen below.

![after_sitting](https://github.com/user-attachments/assets/6a45159c-edd5-4570-8d49-3879da998328)
![after_notsitting](https://github.com/user-attachments/assets/bbb8c607-92b6-4e3e-bd6a-bb9e37aaec2a) ![after_boxes](https://github.com/user-attachments/assets/07930698-729f-46d3-aa62-c5f61bf1e7fd)

This fixes the issue with positioning of the characters on the object but changes the footprint of the object from 3x3 to 4x3. I was not able to find avali settlements to check how this change affects the generation of this object there.

**Comment by Fevix** [comment]
Unfortunately, a fix like this is likely to break not only generated villages (which I could fix) but also player builds (which I cannot fix).
